// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUqIwqieBQxsqzXnWKISJSw52XLbJxWKk',
    appId: '1:330293988254:web:9d7fdff13400352b41648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    authDomain: 'walletdz-d12e0.firebaseapp.com',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
    measurementId: 'G-5H93D9Z5ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeLnEzq0iSZjfx0R-pgu6cs89Ooyfozq0',
    appId: '1:330293988254:android:0562d6c8bd50fd4141648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAie3hehD-yr_4tOGx0u94JjZL-i16-ROA',
    appId: '1:330293988254:ios:b4dc0ca5e254c5bc41648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
    androidClientId:
        '330293988254-5p93m05gsefgb03j1mrkjrup8ul6nk84.apps.googleusercontent.com',
    iosClientId:
        '330293988254-h6me1one0u8rl1r1o8uam3rco5d7200f.apps.googleusercontent.com',
    iosBundleId: 'com.wallet.dz.kenzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAie3hehD-yr_4tOGx0u94JjZL-i16-ROA',
    appId: '1:330293988254:ios:b4dc0ca5e254c5bc41648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
    androidClientId:
        '330293988254-5p93m05gsefgb03j1mrkjrup8ul6nk84.apps.googleusercontent.com',
    iosClientId:
        '330293988254-h6me1one0u8rl1r1o8uam3rco5d7200f.apps.googleusercontent.com',
    iosBundleId: 'com.wallet.dz.kenzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUqIwqieBQxsqzXnWKISJSw52XLbJxWKk',
    appId: '1:330293988254:web:d1670132490207fa41648f',
    messagingSenderId: '330293988254',
    projectId: 'walletdz-d12e0',
    authDomain: 'walletdz-d12e0.firebaseapp.com',
    databaseURL: 'https://walletdz-d12e0-default-rtdb.firebaseio.com',
    storageBucket: 'walletdz-d12e0.appspot.com',
    measurementId: 'G-1JCVX0JJCZ',
  );
}
